# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MEDITATE' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MEDITATE
  pod 'SwiftLint'
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  target 'MEDITATETests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MEDITATEUITests' do
    # Pods for testing
  end

end
